CREATE GENERATOR GEN_CONTRATANTE_ID START WITH 0 INCREMENT BY 1;
SET GENERATOR GEN_CONTRATANTE_ID TO 0;

CREATE TABLE CONTRATANTE (
    CODIGO              BIGINT NOT NULL,
    NUM_CNPJ            VARCHAR(20),
    NUM_CPF             VARCHAR(20),
    DTA_CADASTRO        TIMESTAMP,
    DTA_NASCIMENTO      TIMESTAMP,
    EMAIL1              VARCHAR(100),
    EMAIL2              VARCHAR(100),
    EMAIL3              VARCHAR(100),
    EST_CIVIL           VARCHAR(50),
    FONE1               VARCHAR(50),
    FONE2               VARCHAR(50),
    FONE3               VARCHAR(50),
    NOME                VARCHAR(50),
    NUM_RAMAL           VARCHAR(20),
    NUM_RG              VARCHAR(20),
    SEXO                VARCHAR(20),
    SOBRE_NOME          VARCHAR(100),
    TIPO_CADASTRO       VARCHAR(100),
    CAMADA_FUNCIONAL    VARCHAR(10),
    CONTRATANTE_STATUS  VARCHAR(60),
    DTA_MUDA_CAMADA     TIMESTAMP,
    REGISTRO_NATIVO     VARCHAR(20)
);

ALTER TABLE CONTRATANTE ADD CONSTRAINT PK_CONTRATANTE PRIMARY KEY (CODIGO);

/* Trigger: CONTRATANTE_BI */
SET TERM ^ ;

CREATE OR ALTER TRIGGER CONTRATANTE_BI FOR CONTRATANTE
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.codigo is null) then
    new.codigo = gen_id(gen_contratante_id,1);
end
^

SET TERM ; ^