CREATE GENERATOR GEN_USUARIO_ID START WITH 0 INCREMENT BY 1;
SET GENERATOR GEN_USUARIO_ID TO 0;

CREATE TABLE USUARIO (
    CODIGO              BIGINT NOT NULL,
	CURRENT_PASSWORD 	VARCHAR(255),
    LEVEL_ROLE 			VARCHAR(255),
    USER_ENABLE 		SMALLINT,
    DTA_LAST_CHANGE 	TIMESTAMP,
    LAST_PASSWORD 		VARCHAR(255),
    NUM_CNPJ            VARCHAR(255),
    NUM_CPF             VARCHAR(255),
    DTA_CADASTRO        TIMESTAMP,
    DTA_NASCIMENTO      TIMESTAMP,
    EMAIL1              VARCHAR(255),
    EMAIL2              VARCHAR(255),
    EMAIL3              VARCHAR(255),
    EST_CIVIL           VARCHAR(255),
    FONE1               VARCHAR(255),
    FONE2               VARCHAR(255),
    FONE3               VARCHAR(255),
    NOME                VARCHAR(255),
    NUM_RAMAL           VARCHAR(255),
    NUM_RG              VARCHAR(255),
    SEXO                VARCHAR(255),
    SOBRE_NOME          VARCHAR(255),
    TIPO_CADASTRO       VARCHAR(255),
    CAMADA_FUNCIONAL    VARCHAR(10),
    USUARIO_STATUS  	VARCHAR(60),
    DTA_MUDA_CAMADA     TIMESTAMP,
    REGISTRO_NATIVO     VARCHAR(255)
);

ALTER TABLE USUARIO ADD CONSTRAINT PK_USUARIO PRIMARY KEY (CODIGO);

/* Trigger: USUARIO_BI */
SET TERM ^ ;

CREATE OR ALTER TRIGGER USUARIO_BI FOR USUARIO
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.codigo is null) then
    new.codigo = gen_id(gen_usuario_id,1);
end
^

SET TERM ; ^